language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t joseph/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true joseph/docker-fullstack-app npm run test

after-success:
    - docker build -t joseph/docker-frontend ./frontend
    - docker build -t joseph/docker-backend ./backend
    - docker build -t joseph/docker-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -t "$DOCKER_HUB_ID" --password-stdin

    - docker push joseph/docker-frontend
    - docker push joseph/docker-backend
    - docker push joseph/docker-nginx